### ISSUE TITLE
Unable to upload csv file in UI

### ISSUE THREAD

**Issue by Satishkumar44** [gretelai/gretel-python-client#56]
Hi  sorry the delay in the response 
iam uploading safecast data what do we have in the ui as sample data i downloaded it and tried importing again in the ui which is when iam facing the issue

**Comment by Satishkumar44** [comment]
![16062116414114646057344964241357](https://user-images.githubusercontent.com/60460487/100078074-1d1fd000-2e69-11eb-84c6-6da9fb8f7d68.jpg)

**Comment by johntmyers** [comment]
Thanks @Satishkumar44 can you upload the SyntheticData CSV to this issue?

**Comment by Satishkumar44** [comment]
[data.xlsx](https://github.com/gretelai/gretel-python-client/files/5594651/data.xlsx)
Hi uploaded the file in excel format,But i converted into csv while uploading into Ui.

**Comment by johntmyers** [comment]
@Satishkumar44 I opened this file and converted it to CSV and was able to upload it. It would be best if you uploaded your actual converted CSV since there are different versions of Excel that might behave differently. You can zip the CSV and upload to GitHub.

I'm using a Mac, but I did this:

![image](https://user-images.githubusercontent.com/9696606/100230511-cdd2b180-2ef3-11eb-83cc-9af953a83219.png)

I've attached my resulting CSV here.

[data-converted.csv.zip](https://github.com/gretelai/gretel-python-client/files/5596773/data-converted.csv.zip)

**Comment by Satishkumar44** [comment]
Hi i have converted into CSV and try to upload iam getting the same error. iam using windows
![Screenshot (53)](https://user-images.githubusercontent.com/60460487/100232651-a230e500-2f4e-11eb-8d48-fdaa3f7d585f.png)
![Screenshot (68)](https://user-images.githubusercontent.com/60460487/100232742-c260a400-2f4e-11eb-81a4-c903e179c550.png)
And my excel version-Excel@2019 16.0.13328

**Comment by johntmyers** [comment]
@Satishkumar44 please zip and upload the CSV you have created. We cannot reproduce the problem so need the actual data you are trying to upload.

**Comment by johntmyers** [comment]
Could also try uploading the version I created? https://github.com/gretelai/gretel-python-client/files/5596773/data-converted.csv.zip

**Comment by Satishkumar44** [comment]
With your data also iam getting same error
![Screenshot (69)](https://user-images.githubusercontent.com/60460487/100234218-c261a380-2f50-11eb-8a9b-f84cb2736187.png)
[data.zip](https://github.com/gretelai/gretel-python-client/files/5596949/data.zip)

**Comment by Satishkumar44** [comment]
I have also attached my data also in zip format

**Comment by johntmyers** [comment]
Thanks. We are going to try on Windows. Your data works for me on Mac OS using Chrome and Safari. We are going to test with Windows.

**Comment by johntmyers** [comment]
@Satishkumar44 we may have found what is causing the issue on Windows. Working on a fix and then will test and keep you updated. Thanks for reporting!

**Comment by Satishkumar44** [comment]
Thankyou for the update looking forward to it.

**Comment by johntmyers** [comment]
@Satishkumar44 we have pushed a fix for this, could you try logging out, refreshing the page, logging in and trying again?

**Comment by Satishkumar44** [comment]
After trying the above mentioned steps the issue still persists and giving same error as before.

**Comment by johntmyers** [comment]
Can you try restarting your browser? Just re-tried it on Chrome on Windows

![image](https://user-images.githubusercontent.com/9696606/100243675-227e2880-2f04-11eb-85fc-9ac7f5d3c271.png)

**Comment by Satishkumar44** [comment]
![IMG-20201125-WA0004](https://user-images.githubusercontent.com/60460487/100246867-b3362200-2f5f-11eb-9fb6-aa3cc14ba514.jpg)
I have logged out and logged in and refreshed it iam also using chrome only

**Comment by johntmyers** [comment]
Something might be cached. Have you totally exited the browser?

**Comment by johntmyers** [comment]
Also a hard refresh might help?

**Comment by Satishkumar44** [comment]
Nothing helped as of now i switched to edge and 
IE as well but same error exists.

**Comment by johntmyers** [comment]
@Satishkumar44 looks like this only is happening on Windows machines with Excel installed. The browser is not interpreting the MIME type of the CSV as `text/csv` but as something different. We are able to re-produce and working on another fix now.

**Comment by johntmyers** [comment]
@Satishkumar44 we pushed another patch that should support these MIME types, please log out, refresh, and try again and let us know.

**Comment by Satishkumar44** [comment]
Yes its working fine now .Thankyou for the support
